import { Link } from 'react-router-dom';
import { getTheme, decoBgStyle } from '../theme.js';

function TermsOfService({ isDarkMode }) {
  const theme = getTheme(isDarkMode);

  return (
    <div className="min-h-screen pb-16" style={decoBgStyle(theme)}>
      <div className="px-6 pt-14 pb-6 max-w-3xl mx-auto text-center animate-fade-in-up">
        <p className="text-xs font-['Montserrat'] tracking-[0.3em] uppercase mb-3" style={{ color: theme.accent }}>
          ✦ The Fine Print ✦
        </p>
        <h1 className="font-['Bodoni_Moda'] text-4xl" style={{ color: theme.accent }}>
          Terms of Service
        </h1>
      </div>

      <div className="px-6 max-w-3xl mx-auto">
        <div className="ziggurat-frame animate-fade-in-up" style={{ '--frame-color': theme.accent }}>
          <div className="ziggurat-inner p-8 md:p-10 font-['Montserrat'] text-sm leading-relaxed space-y-4" style={{ backgroundColor: theme.panel, color: theme.text }}>
            <p>
              LinConference Hub is a demonstration project built for an internship assignment. It is not a
              commercial product, and using it does not create any binding agreement.
            </p>
            <p>
              <strong style={{ color: theme.accent }}>No Real Events:</strong> All conferences, speakers, and venues
              listed on this site are fictional and used for demonstration purposes only. Registering for a
              conference here does not grant admission to any real event.
            </p>
            <p>
              <strong style={{ color: theme.accent }}>Accounts:</strong> Since accounts are stored only in your
              browser's local storage, they are not secure in the way a production system would be, and may be
              lost if you clear your browser data.
            </p>
            <p>
              <strong style={{ color: theme.accent }}>AI Assistant:</strong> Responses from the chatbot are
              generated by a third-party AI model and may occasionally be inaccurate or unavailable.
            </p>
            <p>
              This site is provided as-is, for demonstration and educational purposes, with no guarantee of
              uptime, accuracy, or data persistence.
            </p>
          </div>
        </div>

        <p className="text-center mt-6 font-['Montserrat'] text-sm">
          <Link to="/" className="hover:underline" style={{ color: theme.accent }}>
            ← Back to Home
          </Link>
        </p>
      </div>
    </div>
  );
}

export default TermsOfService;